const carData = {
  brandsAndModels: {
    BMW: [
      '3 Series',
      '5 Series',
      'X5',
      'X3',
      '7 Series',
      'X1',
      'X7',
      'X6',
      '4 Series',
      '2 Series',
      'i3',
      'i8',
      'M3',
      'M5',
      'Z4',
    ],
    Toyota: [
      'Camry',
      'Corolla',
      'RAV4',
      'Prius',
      'Highlander',
      'Tacoma',
      'Sienna',
      '4Runner',
      'Yaris',
      'Avalon',
      'Tundra',
      'Land Cruiser',
      'C-HR',
      'Sequoia',
      'Supra',
    ],
    'Mercedes-Benz': [
      'C-Class',
      'E-Class',
      'GLE',
      'GLC',
      'S-Class',
      'A-Class',
      'GLA',
      'GLB',
      'CLA',
      'GLS',
      'SL',
      'G-Class',
      'EQC',
      'AMG GT',
      'Metris',
    ],
    Ford: [
      'Mustang',
      'F-150',
      'Escape',
      'Explorer',
      'Focus',
      'Fusion',
      'Edge',
      'Expedition',
      'Ranger',
      'EcoSport',
      'Transit',
      'Bronco',
      'Fiesta',
      'Flex',
      'Taurus',
    ],
    Honda: [
      'Civic',
      'Accord',
      'CR-V',
      'Pilot',
      'Odyssey',
      'Fit',
      'HR-V',
      'Ridgeline',
      'Insight',
      'Passport',
      'Clarity',
      'Crosstour',
      'S2000',
      'Prelude',
      'Element',
    ],
    Chevrolet: [
      'Silverado',
      'Tahoe',
      'Malibu',
      'Equinox',
      'Traverse',
      'Camaro',
      'Suburban',
      'Impala',
      'Colorado',
      'Cruze',
      'Trailblazer',
      'Spark',
      'Volt',
      'Trax',
      'Express',
    ],
    Volkswagen: [
      'Golf',
      'Jetta',
      'Passat',
      'Tiguan',
      'Atlas',
      'Beetle',
      'Touareg',
      'Arteon',
      'Atlas Cross Sport',
      'ID.4',
      'e-Golf',
      'Golf GTI',
      'Golf R',
      'Golf SportWagen',
      'Atlas Sport',
    ],
    Audi: ['A4', 'Q5', 'A6', 'Q7', 'Q3', 'A3', 'A5', 'Q8', 'A7', 'S5', 'RS Q8', 'RS 3', 'RS 6', 'TT', 'e-tron'],
    Nissan: [
      'Altima',
      'Rogue',
      'Sentra',
      'Pathfinder',
      'Versa',
      'Maxima',
      'Murano',
      'Titan',
      'Frontier',
      'Armada',
      'Leaf',
      'Kicks',
      '370Z',
      'GT-R',
      'NV200',
    ],
    Subaru: ['Outback', 'Forester', 'Impreza', 'Crosstrek', 'Legacy', 'WRX', 'Ascent', 'BRZ', 'XV', 'Baja', 'Tribeca'],
  },
};

export default carData;
